Уровень 0


Придумайте матрицы, которые обладают следующими свойствами:

a) диагональная, ортогональная, но не единичная(!):

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

In [1]:
import numpy as np

In [2]:
m = np.diag([1, -1, -1])
print(m)

[[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]


In [3]:
k = m.transpose() # транспонированная матрица
k

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [4]:
m.dot(k) # проверяем на оргтогональность

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

b) верхнетреугольная, ортогональная:


In [5]:
a = np.array([[-1, 0, 0], [0, 1, 0], [0, 0, -1]])
print(a)

[[-1  0  0]
 [ 0  1  0]
 [ 0  0 -1]]


In [6]:
a.dot(a.T) # проверяем на оргтогональность

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

c) нижнетреугольная, ортогональная:

In [7]:
b = np.array([[-1, 0, 0], [0, -1, 0], [0, 0, -1]])
b

array([[-1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [8]:
b.dot(b.T) # проверяем на оргтогональность

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

d) матрица, у которой определитель = 1, и все элементы не равны 0:

In [9]:
c = np.array([[4, 1/3], [3, 1/2]])
det = np.linalg.det(a)
print(c)
print(det)

[[4.         0.33333333]
 [3.         0.5       ]]
1.0


Найдите собственные значения и собственные вектора матриц:

m = np.array([[2, 2],
[1, 3]])

print(m)

In [10]:
l = np.array([[2, 2], [1, 3]])
l

array([[2, 2],
       [1, 3]])

In [11]:
w, v = np.linalg.eig(l)
w, v

(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

In [12]:
for i in range(len(w)):
    print("Собственное значение " + str(w[i]))
    print("соответствующий ему собственный вектор " + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]


Уровень 1:

Найдите спектральное разложение матрицы:

m = np.array([[1, 2],
[2,3]])

print(m)

In [13]:
m = np.array([[1, 2], [2,3]])
print(m)

[[1 2]
 [2 3]]


In [14]:
w, v = np.linalg.eig(m)
print('Собственные значения:')
print(w)
print('\nСобственные векторы:')
print(v)

Собственные значения:
[-0.23606798  4.23606798]

Собственные векторы:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [15]:
w_d = np.diag(w) # диагональная М из собственных значений
w_d

array([[-0.23606798,  0.        ],
       [ 0.        ,  4.23606798]])

In [16]:
s = np.array(v.dot(w_d).dot(v.T), dtype=float) 
# М из собственных векторов*диагональная М из собственных значений*транспонированная форма М из собственных векторов
s

array([[1., 2.],
       [2., 3.]])