In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',]


In [ ]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [ ]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(1, 3))
X2 = vectorizer2.fit_transform(corpus)
print(vectorizer2.get_feature_names())
print(X2.toarray())

['and', 'and this', 'and this is', 'document', 'document is', 'document is the', 'first', 'first document', 'is', 'is the', 'is the first', 'is the second', 'is the third', 'is this', 'is this the', 'one', 'second', 'second document', 'the', 'the first', 'the first document', 'the second', 'the second document', 'the third', 'the third one', 'third', 'third one', 'this', 'this document', 'this document is', 'this is', 'this is the', 'this the', 'this the first']
[[0 0 0 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 1 1 0 0]
 [0 0 0 2 1 1 0 0 1 1 0 1 0 0 0 0 1 1 1 0 0 1 1 0 0 0 0 1 1 1 0 0 0 0]
 [1 1 1 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 1 0 0 1 1 0 0]
 [0 0 0 1 0 0 1 1 1 0 0 0 0 1 1 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1]]


## TFIDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X)

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
  (0, 1)	0.46979138557992045
  (0, 2)	0.5802858236844359
  (0, 6)	0.38408524091481483
  (0, 3)	0.38408524091481483
  (0, 8)	0.38408524091481483
  (1, 5)	0.5386476208856763
  (1, 1)	0.6876235979836938
  (1, 6)	0.281088674033753
  (1, 3)	0.281088674033753
  (1, 8)	0.281088674033753
  (2, 4)	0.511848512707169
  (2, 7)	0.511848512707169
  (2, 0)	0.511848512707169
  (2, 6)	0.267103787642168
  (2, 3)	0.267103787642168
  (2, 8)	0.267103787642168
  (3, 1)	0.46979138557992045
  (3, 2)	0.5802858236844359
  (3, 6)	0.38408524091481483
  (3, 3)	0.38408524091481483
  (3, 8)	0.38408524091481483


##word2vec

In [ ]:
!wget https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz

--2020-11-27 23:57:42--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.48.46
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.48.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1647046227 (1.5G) [application/x-gzip]
Saving to: ‘GoogleNews-vectors-negative300.bin.gz’

GoogleNews-vectors- 100%[===================>]   1.53G  45.9MB/s    in 35s     

2020-11-27 23:58:17 (45.0 MB/s) - ‘GoogleNews-vectors-negative300.bin.gz’ saved [1647046227/1647046227]



In [ ]:
from gensim.models import KeyedVectors
# load the google word2vec model
filename = 'GoogleNews-vectors-negative300.bin.gz'
model = KeyedVectors.load_word2vec_format(filename, binary=True)
# calculate: (king - man) + woman = ?
result = model.most_similar(positive=['woman', 'king'], negative=['man'], topn=10)
print(result)

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('queen', 0.7118192911148071), ('monarch', 0.6189674139022827), ('princess', 0.5902431011199951), ('crown_prince', 0.5499460697174072), ('prince', 0.5377321243286133), ('kings', 0.5236844420433044), ('Queen_Consort', 0.5235945582389832), ('queens', 0.518113374710083), ('sultan', 0.5098593235015869), ('monarchy', 0.5087411999702454)]


## Наивный баес


In [ ]:
#Загружаем данные и разархивируем

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip

--2020-09-22 22:39:20--  https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 203415 (199K) [application/x-httpd-php]
Saving to: ‘smsspamcollection.zip’

smsspamcollection.z 100%[===================>] 198.65K   994KB/s    in 0.2s    

2020-09-22 22:39:21 (994 KB/s) - ‘smsspamcollection.zip’ saved [203415/203415]



In [ ]:
!unzip smsspamcollection.zip

Archive:  smsspamcollection.zip
  inflating: SMSSpamCollection       
  inflating: readme                  


In [ ]:
import torch
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_table('SMSSpamCollection',sep='\t',header=None, names=['label','sms_message'])

In [ ]:
#Данные 

In [ ]:
df.head()

label                                        sms_message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
#заменяем целевую переменную

In [ ]:
df['label'] = df.label.map({'ham':0,'spam':1})

In [ ]:
#Делим на трейновую и тестовую выборку
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['sms_message'], df['label'], random_state=1)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
#Считаем количество слов в предложениях
#получим матрицу размером (количество предложений Х размер словаря)

count_vector = CountVectorizer()
training_data = count_vector.fit_transform(X_train).toarray().astype('float')
testing_data = count_vector.transform(X_test).toarray().astype('float')

# переводим в тензоры
train_tensor = torch.tensor(training_data)
test_tensor = torch.tensor(testing_data)

In [ ]:
# размер трейновой выборки
training_data.shape

(4179, 7456)

In [ ]:
# всего слов в предложениях
train_tensor.sum()

tensor(59839., dtype=torch.float64)

In [ ]:
# тензор с предложениями класса spam
spam_train_tensor = train_tensor[(y_train == 1).values]

# тензор с предложениями класса not_spam
not_spam_train_tensor = train_tensor[(y_train == 0).values]

In [ ]:

#Вероятность слова при условии что предложение спам
p_w_spam = (spam_train_tensor.sum(axis=0)) / (spam_train_tensor.sum())

#Вероятность слова при условии что предложение не спам
p_w_not_spam = (not_spam_train_tensor.sum(axis=0)) / (not_spam_train_tensor.sum())


In [ ]:
# вероятность, что любое сообщение спам
p_spam = (y_train == 1).values.sum() / len(y_train)

# вероятность, что любое сообщение не спам
p_not_spam = (y_train == 0).values.sum() / len(y_train)

In [ ]:
#проверим на одном семпле
test_sample = test_tensor[0]

In [ ]:
# посчитает значение за спам 
# пляски с прибавлением числа e и вычитания единицы используются для того,
# что бы небыло минус бесконечности после взятия логарифма и суммировались неотрицательные значения
np.log(p_spam+2.71828182846)-1 + (((test_sample*p_w_spam)+2.71828182846).log()-1).sum()

tensor(0.0535, dtype=torch.float64)

In [ ]:
#посчитаем значение против спама
np.log(p_not_spam+2.71828182846)-1 + (((test_sample*p_w_not_spam)+2.71828182846).log()-1).sum()

tensor(0.2841, dtype=torch.float64)

In [ ]:
# видно что значение против спама больше, чем значение за спам 
# соответственно значение не спам

In [ ]:
#посчитаем для всей тестовой выборки

#размер тестовой выборки
test_tensor.shape

torch.Size([1393, 7456])

In [ ]:
#посчитаем предсказания как сравнение величинв за спам и против спама
y_pred = (np.log(p_spam+2.71828182846)-1 + (((test_tensor*p_w_spam)+2.71828182846).log()-1).sum(dim=1)) >= \
 np.log(p_not_spam+2.71828182846)-1 + (((test_tensor*p_w_not_spam)+2.71828182846).log()-1).sum()

In [ ]:
# предсказанные значения
y_pred.int()

tensor([0, 0, 0,  ..., 0, 0, 0], dtype=torch.int32)

In [ ]:
#истиные значение
y_test.to_numpy()

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
#сравним реальные метки с предсказанными
test = (y_pred == torch.tensor(y_test.to_numpy()))

In [ ]:
#посчитаем точность модели как отношение количество совпадений к размеру выборки  
test.sum().item()/test.shape[0]

0.8671931083991385